name: Test
on: push
jobs:
  job:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2    
    - name: Set up JVM
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: adopt
    - name: Run tests
      run: sbt test
